#!/bin/sh
# branch-inventory.sh: generates the remote branch inventory that
# program/README.md used to carry hand-typed, pinned to a sha and a branch
# list that both went stale the moment anyone pushed, merged, or deleted a
# branch after the table was written.
#
# Why this exists: a hand-written inventory rots silently. This script
# answers the same two questions mechanically, every time it runs: which
# branches exist on origin right now (`git ls-remote --heads origin`), and
# is each one merged into origin/main (`git merge-base --is-ancestor
# origin/<branch> origin/main`). It prints the origin/main sha it measured
# at, so the table it produces can never outlive the commit it names: paste
# fresh output instead of editing the sha by hand.
#
# What this does NOT do: it does not explain WHY a branch is unmerged, what
# work it holds, or whether it is safe to delete. Read the branch's own
# commits for that. It does not fetch or modify the repository; if a local
# remote-tracking ref (`origin/<branch>`) is missing or stale because this
# clone has not fetched recently, the branch is reported UNKNOWN rather than
# guessed at, and `git fetch origin --prune` is named as the fix. It talks
# to origin over git only (`git ls-remote`, `git rev-list`, `git
# merge-base`), never `gh`, never curl.
#
# POSIX sh only, no bashisms: no arrays, no [[ ]], no local, no process
# substitution, no here-strings.
#
# Usage, from anywhere inside the repository:
#   scripts/branch-inventory.sh

set -e

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
cd "$ROOT"

if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "branch-inventory.sh: not inside a git work tree" >&2
    exit 1
fi

if ! MAIN_SHA=$(git rev-parse -q --verify origin/main 2>/dev/null); then
    echo "branch-inventory.sh: no local origin/main ref; run" \
         "'git fetch origin --prune' first" >&2
    exit 1
fi

WORKDIR=$(mktemp -d 2>/dev/null || echo "/tmp/sbe-branch-inventory-work.$$")
mkdir -p "$WORKDIR"
trap 'rm -rf "$WORKDIR"' EXIT INT TERM

git ls-remote --heads origin > "$WORKDIR/heads"

echo "Branch inventory, generated by scripts/branch-inventory.sh"
echo "origin/main is $MAIN_SHA"
echo ""
printf '%-38s %-8s %6s %6s %s\n' "Branch" "Status" "Ahead" "Behind" "Head sha"

while read -r sha ref; do
    [ -z "$ref" ] && continue
    branch=${ref#refs/heads/}
    [ "$branch" = "main" ] && continue

    if ! git rev-parse -q --verify "origin/$branch" >/dev/null 2>&1; then
        printf '%-38s %-8s %6s %6s %s\n' "$branch" "UNKNOWN" "-" "-" "$sha"
        continue
    fi

    if git merge-base --is-ancestor "origin/$branch" "$MAIN_SHA" 2>/dev/null; then
        status="merged"
    else
        status="unmerged"
    fi

    ahead=$(git rev-list --count "$MAIN_SHA..origin/$branch" 2>/dev/null || echo "?")
    behind=$(git rev-list --count "origin/$branch..$MAIN_SHA" 2>/dev/null || echo "?")

    printf '%-38s %-8s %6s %6s %s\n' "$branch" "$status" "$ahead" "$behind" "$sha"
done < "$WORKDIR/heads"
